######## AUTHORS ########

### ADD AUTHOR
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "mutation { addAuthor(name: \"J. K. Rowling\") { id name } }"
}

### GET AUTHOR
POST http://localhost:3000/graphql
Content-Type: application/json

# {
#   "query": "{ author(id: \"67d6161ab34a5c844f9f817d\") { id name } }"
# }

{
  "query": "query getAuthor($id: ID!) { author(id: $id) { id name books { id title } } }",
  "variables": {
    "id": "67d63e0ee21a69565b84d01e"
  }
}

### GET AUTHORS
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "{ authors { id name books { id title } } }"
}

######## BOOKS ########

### ADD BOOK
POST http://localhost:3000/graphql
Content-Type: application/json

# {
#   "query": "mutation { addBook(title: \"Harry Potter and the Sorcerer's Stone\", authorId: \"67d74330cbc452efc55d74bb\", publishedDate: \"1997-06-26\") { id title publishedDate authorId } }"
# }

# {
#   "query": "mutation { addBook(title: \"Harry Potter and the Chamber of Secrets\", authorId: \"67d74330cbc452efc55d74bb\", publishedDate: \"1998-07-02\") { id title publishedDate author { id name } } }"
# }

{
  "query": "mutation { addBook(title: \"The Hobbit\", authorId: \"67d6161ab34a5c844f9f817d\", publishedDate: \"1937-09-21\") { id title publishedDate author { id name } } }"
}

### GET BOOKS
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "{ books { id title author { id name } } }"
}

### GET BOOK
POST http://localhost:3000/graphql
Content-Type: application/json

{
  "query": "{ book(id: \"67d64acc717611955cf6a50e\") { title author { id name } } }"
}

### EDIT BOOK
POST http://localhost:3000/graphql
Content-Type: application/json

# {
#   "query": "mutation { editBook(id: \"67d7454ccbc452efc55d74c2\", title: \"The Hobbit\", authorId: \"67d6161ab34a5c844f9f817d\", publishedDate: \"1937-09-21\", imageUrl: \"https://m.media-amazon.com/images/I/918wRKAO+cL._AC_UL320_.jpg\") { id title author { id name } publishedDate imageUrl } }"
# }

{
  "query": "mutation { editBook(id: \"67d64acc717611955cf6a50e\", title: \"O Senhor dos Anéis: As duas torres\", imageUrl: \"https://m.media-amazon.com/images/I/81lQ5N0QwJL._AC_UL320_.jpg\", publishedDate: \"1954-11-11\") { id title author { id name } publishedDate imageUrl } }"
}

